# Generated by Django 4.2.7 on 2024-02-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistent_chatgpt', '0006_rename_bot_key_business_assistent_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.business')),
            ],
        ),
    ]
