# Generated by Django 4.2.7 on 2024-02-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0006_rename_bot_key_business_assistent_key_and_more'),
        ('socials_chatbots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramTokens',
            new_name='TelegramToken',
        ),
    ]
