# Generated by Django 4.2.7 on 2024-02-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0006_rename_bot_key_business_assistent_key_and_more'),
        ('socials_chatbots', '0002_rename_telegramtokens_telegramtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.business')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.origin')),
            ],
            options={
                'unique_together': {('origin', 'business')},
            },
        ),
    ]
