# Generated by Django 4.2.7 on 2024-02-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials_chatbots', '0003_welcomemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
