# Generated by Django 4.2.7 on 2024-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refaccionariax',
            options={'verbose_name': 'Refaccionaria X Product', 'verbose_name_plural': 'Refaccionaria X Products'},
        ),
        migrations.AddField(
            model_name='refaccionariax',
            name='estante',
            field=models.CharField(default='', max_length=100),
        ),
    ]
