# Generated by Django 4.2.7 on 2024-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0002_alter_refaccionariax_options_refaccionariax_estante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccionariax',
            name='estante',
            field=models.CharField(max_length=100),
        ),
    ]
