# Generated by Django 4.2.7 on 2024-01-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0003_alter_business_options'),
        ('business_data', '0003_alter_refaccionariax_estante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='files/')),
                ('file_type', models.IntegerField(choices=[(1, 'excel'), (2, 'csv'), (3, 'json'), (4, 'xml'), (5, 'access')])),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.business')),
            ],
        ),
    ]
