# Generated by Django 4.2.7 on 2024-01-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0005_rename_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
