# Generated by Django 4.2.7 on 2024-01-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0008_alter_refaccionariax_bussiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refaccionariax',
            name='bussiness',
        ),
    ]
