# Generated by Django 4.2.7 on 2024-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0010_refaccionariay'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefaccionariaGonzales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('compoatibility', models.CharField(max_length=100)),
                ('motor_l', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Refaccionaria Gonzales Product',
                'verbose_name_plural': 'Refaccionaria Gonzales Products',
            },
        ),
    ]
