# Generated by Django 4.2.7 on 2024-02-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0011_refaccionariagonzales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refaccionariagonzales',
            old_name='compoatibility',
            new_name='compatibility',
        ),
    ]
