# Generated by Django 4.2.7 on 2024-02-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0013_rename_descripcion_refaccionariagonzales_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refaccionariagonzales',
            name='description',
        ),
    ]
