# Generated by Django 4.2.7 on 2024-02-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0015_alter_refaccionariagonzales_compatibility'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefaccionariaGonzales',
            new_name='RefaccionariaGonzalez',
        ),
    ]
