# Generated by Django 4.2.7 on 2024-02-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0016_rename_refaccionariagonzales_refaccionariagonzalez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refaccionariagonzalez',
            name='model',
        ),
        migrations.RemoveField(
            model_name='refaccionariagonzalez',
            name='motor_l',
        ),
    ]
