# Generated by Django 4.2.7 on 2024-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0018_remotefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccionariagonzalez',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
