# Generated by Django 4.2.7 on 2024-02-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0019_alter_refaccionariagonzalez_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteFile',
        ),
    ]
