# Generated by Django 4.2.7 on 2024-02-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0003_alter_business_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.business', unique=True),
        ),
        migrations.RemoveField(
            model_name='bot',
            name='origin',
        ),
    ]
