# Generated by Django 4.2.7 on 2024-02-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0004_alter_bot_unique_together_alter_bot_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bot_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
