# Generated by Django 4.2.7 on 2024-02-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0005_business_bot_key_delete_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bot_key',
            new_name='assistent_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='chat',
            new_name='chat_key',
        ),
    ]
