# Generated by Django 4.2.7 on 2024-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0006_rename_bot_key_business_assistent_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
