# Generated by Django 4.2.7 on 2024-02-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0007_business_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file_link', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistent_chatgpt.business')),
            ],
        ),
    ]
