# Generated by Django 4.2.7 on 2024-02-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0008_datafiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataFiles',
            new_name='DataFile',
        ),
    ]
