# Generated by Django 4.2.7 on 2024-03-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0010_delete_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='openai_apikey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
