# Generated by Django 4.2.7 on 2024-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0011_business_openai_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
