# Generated by Django 4.2.7 on 2024-03-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0014_alter_instruction_instruction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='index',
        ),
    ]
