# Generated by Django 4.2.7 on 2024-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0018_business_end_message_1_business_end_message_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
