# Generated by Django 4.2.7 on 2024-03-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistent_chatgpt', '0019_user_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_messages_sent',
            field=models.BooleanField(default=False),
        ),
    ]
